<p>We at NANO understand that if you sell high volume and low cost items then it is a costly process to build a true 3D model of your entire stock range.
You would need to ensure that you sell a lot more items to justify the cost. For our clients that fall into this category we have created flash based
applications that will quickly enable you to benefit from 3D internet. They allow your customers to have a 360 degree view of your products. 
<br/><br/>
GIGA models are ideal for asymmetric products or for creating a useful and visually engaging catalogue of items.</p>

<p>3D isn't just about what is in front of you, it's also what's around you. NANO have developed another flash application that
will display flat images of panoramas with depth.
<br/><br/>
This means that we are able to take your own pictures of views or rooms and dynamically warp them so that an illusion of depth is created.
The beauty of this is that no special cameras are required to take pictures and no cumbersome plug-in needs to be downloaded to view the results.</p>