<p>Didn't your mother ever tell you to look with your eyes and not with your hands? Well sometimes pictures just aren't good enough especially
when products are asymmetric or they have a great number of deign features. What NOVA will allow you to do is display all your products key
component at the same time and allow your customers to get the information that is most relevant to them. NOVA will allow you to view items from
any angle, from close up or from far away. You can even change the colour scheme at the click of a button.</p>

<p>As is the case with all of the NANO products NOVA solutions are designed to be modular, so as they can be easily plugged into an
existing site by your own developers or by ourselves, and they are also designed to be transposed onto an interactive CD-ROM. To see
an example of just some of the capabilities of the NOVA range click on the demo button to view online or you can download a version here</p>
