<p>An important part of any business is promotion and marketing. A great way to increase your company profile is with the use
of promotional games as part of a viral marketing campaign. As is the case with all the NANO products PETA products can be transposed
onto CD-ROM.
<br/><br/>
High scores make such good water cooler conversation, and so will your company.</p>

<p>We've all had those moments in the office when we take an internet break, check email browse for fun and play games.
The games we create at NANO are for just those times, fun games that can be downloaded played online or sent to a friend.
This means that your company brand will gain a natural and non-spam coverage. The games are bespoke to your company so they
will represent your unique image in fun way.</p>
