<p>These are the top end solutions that NANO provide. The TERA range allows our clients to fully utilise the power of broadband and
3D internet technologies to deliver the most engaging and informative experience to their customers. Nowadays there is an increased need to
present information in a clear and succinct way. Information should be quickly understood
and relevant details be rapidly obtained. While pictures can tell a thousand words 3D can tell the whole story and interactive
3D speaks volumes. It is the interactive capabilities of the TERA line that add the most value to our clients.</p>

<p>The versatility of the TERA solutions mean that virtually anything that can be imagined can be created. So if you want to display a
car where you can change it's colour, open doors press the horn turn on lights and even go for a test drive, it's all possible with TERA. Or
if you want to bring artwork and sculpture to life TERA give you the power to do this. As is the case with all of the NANO products TERA
solutions are designed to be modular, so as they can be easily plugged into an existing site by your own developers or by ourselves, and
they are also designed to be transposed onto an interactive CD-ROM.</p>