<div id="content">

<p id="tagline"><span></span>A picture tells a 1000 words, <span id="second_line"><span></span><abbr title="3 Dimensional">3D</abbr> gives the whole story.</span></p>

<h3></h3>

<p>We are NANO and we specialise in the creation of interactive 3D content for the internet. NANO products are not just for the internet,
they can also be used as part of an interactive CD or as a stand alone application. NANO likes to keep things simple, this is why we believe
in 3D, because while a picture tells a thousand words 3D give the whole story. People view the world in 3D and intuitively understand it. 
</p>

<p>We are able to create fully interactive 3D online representations of your products. Anything from airplanes to apartments, candle holders to
cars and TV's to tractors, in fact anything that you can imagine. Furthermore our products can be integrated in interactive Demo CD's. Great when
it's not always feasible to take your entire product range to demonstrate to clients or vice versa.</p>

<!-- end of div id #content -->
</div>
